### ISSUE TITLE
Inserir campo de desistência de curso - Prioridade baixa (4)

### ISSUE THREAD

**Issue by CarolSPeixoto** [lmtsufape/Ingressa#173]
- Inserir botão para informarmos a desistência de curso. Após isso, o aluno deve sumir da listagem final e o próximo da lista de espera deve aparecer na listagem final.

**Comment by felipe-rodriguess** [comment]
Atualmente não temos uma opção de desistência do curso, precisamos indeferir manualmente todos os documentos do aluno para poder "registrar a desistência" dele.

**Comment by Rener1** [comment]
Mesma issue que a #235
