### ISSUE TITLE
Registro de desistência após o início das aulas - Prioridade baixíssima (5)

### ISSUE THREAD

**Issue by CarolSPeixoto** [lmtsufape/Ingressa#179]
Colocar uma função que, quando a gente registre uma desistência na 1ª Entrada após o início das aulas, o sistema não puxe um candidato da 2ª Entrada. Essa opção se aplica apenas nos cursos que há apenas um turno (BCC, Letras e Engenharia de Alimentos) e justifica-se pelo fato de após determinado tempo de aulas, um aluno não conseguir mais acompanhar o conteúdo e, portanto, não deve ser remanejado da 2ª entrada para a 1ª.

**Comment by felipe-rodriguess** [comment]
Ao registrarmos uma desistência, o sistema poderia perguntar, se a gente quer remanejar, ou não, um aluno da 2ª entrada, nos três cursos específicos (BCC, Letras e Engenharia de Alimentos).

**Comment by Rener1** [comment]
Mesmo do #239
