### ISSUE TITLE
Avaliação dos analistas - Prioridade média (3)

### ISSUE THREAD

**Issue by felipe-rodriguess** [lmtsufape/Ingressa#198]
Criar uma função que possibilite que o administrador habilite quais os cursos e cotas que cada Analista Geral visualizará para realizar a avaliação.

**Comment by Rener1** [comment]
Fazendo esta funcionalidade me deparei com um pequeno problema. As cotas já são filtradas de acordo com o cargo do analista, e dessa forma, podemos ter conflito entre as cotas relacionadas ao cargo do analista e as cotas colocadas manualmente.

![Captura de tela 2024-01-12 155348](https://github.com/lmtsufape/Ingressa/assets/55724549/6b890c59-046f-4fe7-9bf5-a511b99391a0)

Qual deverá ser o comportamento do sistema em caso de conflitos?

1. Cotas colocadas manualmente sobrescrevem as regras do tipo do analista.
2. Somente o analista geral pode ter suas cotas modificadas.
3. Alguma outra coisa.

Também gostaria de saber a diferença entre um analista geral e um analista que é tanto da seção médica quanto da heteroidentificação.

**Comment by felipe-rodriguess** [comment]
1. Somente o analista geral pode ter suas cotas modificadas.

2. Diferença:

2.1. ANALISTA GERAL: Faz a análise apenas dos documentos pessoais e dos comprovantes de renda.
Os analistas gerais não podem analisar a foto, o vídeo e a declaração cotista, essa avaliação é feita exclusivamente pela comissão de heteroidenficação nomeada pela Reitoria.

2.2. ANALISTA MÉDICO: Faz a análise apenas do laudo médico e dos exames.

2.3. ANALISTA DE HETEROIDENTIFICAÇÃO: É um perfil utilizado pelos membros da comissão de heteroidenficação, que fazem a análise apenas da foto, do vídeo e da declaração de cotista.

Na edição passada tivemos uma servidora que atuou como analista geral, mas também foi nomeada para uma comissão de heteroidenficação e tinha os dois perfis.

Qualquer coisa, se tiverem dificuldade em atribuir dois perfis para uma mesma pessoa, podemos utilizar uma saída diferente, utilizando dois e-mails diferente para atribuir perfis diferente para uma mesma pessoa, quando for o caso.

**Comment by felipe-rodriguess** [comment]
Somente o analista geral pode ter suas cotas modificadas, mas é importante haver a possibilidade de distrivuir cursos e cotas diferentes para todas as cotas,. Por exemplo:

ANALISTA GERAL 1: Analisa cotas L1, L2, L5 e L6 de Agronomia, BCC e Letras

ANALISTA GERAL 2: Analisa cotas L1, L2, L5 e L6 de Engenharia, Pedagogia, Veterinária e Zootecnia

ANALISTA MÉDICO 1: Analisa cotas  de L13 e L14 de Agronomia, BCC e Letras

ANALISTA MÉDICO 2: Analisa cotas  de L13 e L14 de Engenharia, Pedagogia, Veterinária e Zootecnia

ANALISTA HETEROIDENFICAÇÃO 1: Analisa cotas  de L9 e L10 de Agronomia, BCC e Letras

ANALISTA HETEROIDENFICAÇÃO 2: Analisa cotas  de L9 e L10 de Engenharia, Pedagogia, Veterinária e Zootecnia

**Comment by Rener1** [comment]
Fiz a funcionalidade considerando que somente o analista geral pode ter suas cotas modificadas. Dessa forma, não é possível modificar as cotas de um analista que possui o tipo geral e o tipo medico ou heteroidentificação simultaneamente.
Está correto @felipe-rodriguess?

**Comment by felipe-rodriguess** [comment]
Tudo bem, @Rener1! Mesmo no caso de um analista que possui o tipo geral e o tipo médico ou heteroidentificação simultaneamente, precisaremos modificar as cotas do analista geral.  Mas da forma que você fez já resolver, pois, nos casos que houver um analista que é geral e heteroidentificação, por exemplo, criamos dois perfis diferentes para ele no Ingressa.
