### ISSUE TITLE
Função para edição de regras de remanejamento - Prioridade Máxima (1)

### ISSUE THREAD

**Issue by felipe-rodriguess** [lmtsufape/Ingressa#211]
Solicitamos a criação de uma função para que os administradores possam alterar as regras de remanejamento de cada cota manualmente.

_**Por exemplo:**

▪ Vagas remanescentes do Grupo L1:
a) Por candidatos do Grupo L9;
b) Restando vagas, por candidatos do Grupo L10;
c) Restando vagas, por candidatos do Grupo L2;
d) Restando vagas, por candidatos do Grupo L14;
e) Restando vagas, por candidatos do Grupo L6;
f) Restando vagas, por candidatos do Grupo L13;
g) Restando vagas, por candidatos do Grupo L5;
h) Restando vagas, por candidatos da Ampla Concorrência._

Atualmente o sistema só permite que seja criado o código da cota, o nome da cota e a distribuição das vagas no curso.

**Comment by Rener1** [comment]
Bom dia @felipe-rodriguess, esta funcionalidade já foi desenvolvida e está pronta. Inclusive, uma issue a respeito já foi aberta: #207.
Acrescentei mais alguns detalhes hoje e pedirei para que as mudanças sejam implantadas no servidor de testes, que pode ser acessado através do link https://lmtsteste02.ufape.edu.br/.
